# -*- coding: utf-8 -*-
"""BFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TTL9GeP0ckbt7RhDMDF8Fo59wFS_VJGR
"""

graph = {
    '5' : ['3','7'],
    '3' : ['2','4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
    }

visited = []  #list for visited noed
queue = []    #Initiated a queue

def bfs(visited, graph, node):    #function for bfs
  visited.append(node)
  queue.append(node)

  while queue:          #creating loop to visit each node
    m = queue.pop(0)
    print(m, end = " ")

    for neighbour in graph[m]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

print("Following is the breadth first search")
bfs(visited, graph, '5')    #function calling