# -*- coding: utf-8 -*-
"""DFS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oioKUjv1VN-nSKvUfG0rJyORf1j2aqLk
"""

graph = {
    '5' : ['3','7'],
    '3' : ['2','4'],
    '7' : ['8'],
    '2' : [],
    '4' : ['8'],
    '8' : []
}

visited = set()     #to keep track of the visited nodes in the graph

def dfs(visited, graph, node):
    if node not in visited:
      print (node)
      visited.add(node)
      for neighbour in graph[node]:
        dfs(visited, graph, neighbour)

print("Following is the Depth First Search")
dfs(visited, graph, '5');